apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/astute-acolyte-451812-c5/sofe3980u/bin # Use repo-path in GKE
          name: binarycalculator
          ports:
            - containerPort: 8080
              name: http
